add bbrun

diff --git a/bin/bbrun b/bin/bbrun
--- a/bin/bbrun
+++ b/bin/bbrun
@@ -1,18 +1,20 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-### bashdoc [ "-"SECTION ] FILES ... Usage:help
+set -euo pipefail
+
+### Bash Builder Runner Usage:help
 #
-# Provide the files you want to print the internal documentation for.
+# Run a Bash Builder script directly without pre-compiling.
 #
-# By default, prints the "bbuild" documentation sections.
+# Suitable for use with a shebang line.
 #
-# To print just the `api` sections, call
+# Incompatible with 'runmain'
 #
-#   bashdoc -api ...
-#
-# To list just available modules, simply run `bashdoc` on its own
+# Set 'DEBUG_mode=true' to see BBPATH used.
 #
 ###/doc
+
+BBRUN_VERSION=1.0
 
 ##bash-libs: tty.sh @ ab570026 (2.1.5)
 
@@ -378,343 +380,265 @@ syntax-extensions:use:local() {
 args:use:local() {
     syntax-extensions:use:local "$@"
 }
+##bash-libs: abspath.sh @ ab570026 (2.1.5)
 
-##bash-libs: autohelp.sh @ ab570026 (2.1.5)
-
-### Autohelp Usage:bbuild
+### abspath:path RELATIVEPATH [ MAX ] Usage:bbuild
+# Returns the absolute path of a file/directory
 #
-# Autohelp provides some simple facilities for defining help as comments in your code.
-# It provides several functions for printing specially formatted comment sections.
-#
-# Write your help as documentation comments in your script
-#
-# To output a named section from your script, or a file, call the
-# `autohelp:print` function and it will print the help documentation
-# in the current script, or specified file, to stdout
-#
-# A help comment looks like this:
-#
-#    ### <title> Usage:help
-#    #
-#    # <some content>
-#    #
-#    # end with "###/doc" on its own line (whitespaces before
-#    # and after are OK)
-#    #
-#    ###/doc
-#
-# It can then be printed from the same script by simply calling
-#
-#   autohelp:print
-#
-# You can print a different section by specifying a different name
-#
-# 	autohelp:print section2
-#
-# > This would print a section defined in this way:
-#
-# 	### Some title Usage:section2
-# 	# <some content>
-# 	###/doc
-#
-# You can set a different comment character by setting the 'HELPCHAR' environment variable.
-# Typically, you might want to print comments you set in a INI config file, for example
-#
-# 	HELPCHAR=";" autohelp:print help config-file.ini
-# 
-# Which would then find comments defined like this in `config-file.ini`:
-#
-#   ;;; Main config Usage:help
-#   ; Help comments in a config file
-#   ; may start with a different comment character
-#   ;;;/doc
-#
-#
-#
-# Example usage in a multi-function script:
-#
-#   #!usr/bin/env bash
-#
-#   ### Main help Usage:help
-#   # The main help
-#   ###/doc
-#
-#   ### Feature One Usage:feature_1
-#   # Help text for the first feature
-#   ###/doc
-#
-#   feature1() {
-#       autohelp:check:section feature_1 "$@"
-#       echo "Feature I"
-#   }
-#
-#   ### Feature Two Usage:feature_2
-#   # Help text for the second feature
-#   ###/doc
-#
-#   feature2() {
-#       autohelp:check:section feature_2 "$@"
-#       echo "Feature II"
-#   }
-#
-#   main() {
-#       case "$1" in
-#       feature1|feature2)
-#           "$1" "$@"            # Pass the global script arguments through
-#           ;;
-#       *)
-#           autohelp:check-no-null "$@"  # Check if main help was asked for, if so, or if no args, exit with help
-#
-#           # Main help not requested, return error
-#           echo "Unknown feature"
-#           exit 1
-#           ;;
-#       esac
-#   }
-#
-#   main "$@"
-#
+# MAX defines the maximum number of "../" relative items to process
+#   default is 50
 ###/doc
 
-### autohelp:print [ SECTION [FILE] ] Usage:bbuild
-# Print the specified section, in the specified file.
-#
-# If no file is specified, prints for current script file.
-# If no section is specified, defaults to "help"
-###/doc
+function abspath:path {
+    local workpath="$1" ; shift || :
+    local max="${1:-50}" ; shift || :
 
-HELPCHAR='#'
+    if [[ "${workpath:0:1}" != "/" ]]; then workpath="$PWD/$workpath"; fi
 
-autohelp:print() {
-    local input_line
-    local section_string="${1:-}"; shift || :
-    local target_file="${1:-}"; shift || :
-    [[ -n "$section_string" ]] || section_string=help
-    [[ -n "$target_file" ]] || target_file="$0"
-
-    local sec_start='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s+(.+?)\s+Usage:'"$section_string"'\s*$'
-    local sec_end='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s*/doc\s*$'
-    local in_section=false
-
-    while read input_line; do
-        if [[ "$input_line" =~ $sec_start ]]; then
-            in_section=true
-            echo -e "\n${BASH_REMATCH[1]}\n======="
-
-        elif [[ "$in_section" = true ]]; then
-            if [[ "$input_line" =~ $sec_end ]]; then
-                in_section=false
-            else
-                echo "$input_line" | sed -r "s/^\s*$HELPCHAR/ /;s/^  (\S)/\1/"
-            fi
-        fi
-    done < "$target_file"
-
-    if [[ "$in_section" = true ]]; then
-            out:fail "Non-terminated help block."
-    fi
+    workpath="$(abspath:collapse "$workpath")"
+    abspath:resolve_dotdot "$workpath" "$max" | sed -r 's|(.)/$|\1|'
 }
 
-### autohelp:paged Usage:bbuild
-#
-# Display the help in the pager defined in the PAGER environment variable
-#
-###/doc
-autohelp:paged() {
-    : ${PAGER=less}
-    autohelp:print "$@" | $PAGER
+function abspath:collapse {
+    echo "$1" | sed -r 's|/\./|/|g ; s|/\.$|| ; s|/+|/|g'
 }
 
-### autohelp:check-or-null ARGS ... Usage:bbuild
-# Print help if arguments are empty, or if arguments contain a '--help' token
-#
-###/doc
-autohelp:check-or-null() {
-    if [[ -z "$*" ]]; then
-        autohelp:print help "$0"
-        exit 0
-    else
-        autohelp:check:section "help" "$@"
-    fi
-}
+function abspath:resolve_dotdot {
+    local workpath="$1"; shift || :
+    local max="$1"; shift || :
 
-### autohelp:check-or-null:section SECTION ARGS ... Usage:bbuild
-# Print help section SECTION if arguments are empty, or if arguments contain a '--help' token
-#
-###/doc
-autohelp:check-or-null:section() {
-    . <(args:use:local section -- "$@") ; 
-    if [[ -z "$*" ]]; then
-        autohelp:print "$section" "$0"
-        exit 0
-    else
-        autohelp:check:section "$section" "$@"
-    fi
-}
-
-### autohelp:check ARGS ... Usage:bbuild
-#
-# Automatically print "help" sections and exit, if "--help" is detected in arguments
-#
-###/doc
-autohelp:check() {
-    autohelp:check:section "help" "$@"
-}
-
-### autohelp:check:section SECTION ARGS ... Usage:bbuild
-# Automatically print documentation for named section and exit, if "--help" is detected in arguments
-#
-###/doc
-autohelp:check:section() {
-    local section arg
-    section="${1:-}"; shift || out:fail "No help section specified"
-
-    for arg in "$@"; do
-        if [[ "$arg" =~ --help ]]; then
-            cols="$(tput cols)"
-            autohelp:print "$section" | fold -w "$cols" -s || autohelp:print "$section"
-            exit 0
-        fi
-    done
-}
-
-##bash-libs: searchpaths.sh @ ab570026 (2.1.5)
-
-# FIXME - set function signature in head of help
-### searchpaths:file_from PATHDEF FILE Usage:bbuild
-#
-# Locate a file along a search path.
-#
-# EXAMPLE
-#
-# The following will look for each of the files
-#  in order of preference of a local lib directory, a profile-wide one, then a system-
-#  wide one.
-#
-#    MYPATH="./lib:$HOME/.local/lib:/usr/local/lib"
-# 	searchpaths:file_from "$MYPATH" file
-#
-# Echoes the path of the first file found.
-#
-# Returns 1 on failure to find any file.
-#
-###/doc
-
-function searchpaths:file_from {
-    local PATHS="$1"; shift || :
-    local FILE="$1"; shift || :
-
-    local oldIFS="$IFS"
-    IFS=$' \t\n'
-
-    for path in $(echo "$PATHS"|tr ':' ' '); do
-        local fpath="$path/$FILE"
-        if [[ -f "$fpath" ]]; then
-            echo "$fpath"
+    # Set a limit on how many iterations to perform
+    # Only very obnoxious paths should fail
+    local obnoxious_counter
+    for obnoxious_counter in $(seq 1 $max); do
+        # No more dot-dots - good to go
+        if [[ ! "$workpath" =~ /\.\.(/|$) ]]; then
+            echo "$workpath"
             return 0
         fi
+
+        # Starts with an up-one at root - unresolvable
+        if [[ "$workpath" =~ ^/\.\.(/|$) ]]; then
+            return 1
+        fi
+
+        workpath="$(echo "$workpath"|sed -r 's@[^/]+/\.\.(/|$)@@')"
     done
 
-    IFS="$oldIFS"
-    return 1
+    # A very obnoxious path was used.
+    return 2
 }
-##bash-libs: runmain.sh @ ab570026 (2.1.5)
+##bash-libs: patterns.sh @ ab570026 (2.1.5)
 
-### runmain SCRIPTNAME FUNCTION [ARGUMENTS ...] Usage:bbuild
+### Useful patterns Usage:bbuild
 #
-# Runs the function FUNCTION with ARGUMENTS, only if the runtime
-# name of the script matches SCRIPTNAME
+# Some useful regex patterns, exported as environment variables.
 #
-# This allows you include a main-like function in your library
-# that only runs if you use your lib as an executabl itself.
+# They are not foolproof, and you are encouraged to improve upon them.
 #
-# For example, an image archiver could be:
-#
-# 	function archive_images {
-# 		tar czf "$1.tgz" "$@"
-# 	}
-#
-# 	runmain archiveimages.sh archive_images "$@"
-#
-# When included a different script, the runmain call does not fire the lib's function
-#
-# If the lib is compiled/made executable, and named "archiveimages.sh", the function runs.
-#
-# This is similar to `if __name__ == "__main__"` clauses in python
+# $PAT_blank - detects whether an entire line is empty or whitespace
+# $PAT_comment - detects whether is a line is a script comment (assumes '#' as the comment marker)
+# $PAT_num - detects whether the string is an integer number in its entirety
+# $PAT_cvar - detects if the string is a valid C variable name
+# $PAT_filename - detects if the string is a safe UNIX or Windows file name;
+#   does not allow presence of whitespace or special characters aside from '_', '.', '-'
+# $PAT_email - simple heuristic to determine whether a string looks like a valid email address
 #
 ###/doc
 
-function runmain {
-    local required_name="$1"; shift || :
-    local funcall="$1"; shift || :
-    local scriptname="$(basename "$0")"
+export PAT_blank='^\s*$'
+export PAT_comment='^\s*(#.*)?$'
+export PAT_num='^[0-9]+$'
+export PAT_cvar='^[a-zA-Z_][a-zA-Z0-9_]*$'
+export PAT_filename='^[a-zA-Z0-9_.-]$'
+export PAT_email="$PAT_filename@$PAT_filename.$PAT_cvar"
 
-    if [[ "$required_name" = "$scriptname" ]]; then
-        "$funcall" "$@"
-    fi
-}
+##bash-libs: debug.sh @ ab570026 (2.1.5)
 
-list_modules() {
-    local thepath f
-    out:info "Available modules: "
+### Debug lib Usage:bbuild
+#
+# Debugging tools and functions.
+#
+# You need to activate debug mode using debug:activate command at the start of your script
+#  (or from whatever point you wish it to activate)
+#
+###/doc
 
-    while read thepath; do
-        out:warn "Checking $thepath"
-        while read f; do
-            if [[ -f "$thepath/$f" ]]; then
-                echo "$f"
-            fi
-        done < <(ls "$thepath") | column
-    done < <(echo "$BBPATH"|sed 's/:/\n/g')
-}
+### Environment Variables Usage:bbuild
+#
+# DEBUG_mode : set to 'true' to enable debugging output
+#
+###/doc
 
-main() {
-    autohelp:check "$@"
+: ${DEBUG_mode=false}
 
-    if [[ -z "$*" ]]; then
-        list_modules
-        exit 0
-    fi
+### debug:mode [output | /output | verbose | /verbose] ... Usage:bbuild
+#
+# Activate debug output (`output`), or activate command tracing (`verbose`)
+#
+# Deactivate with the corresponding `/output` and `/verbose` options
+#
+###/doc
 
-    # ====================================================================
-    # Get the section, if specified.
-
-    SECTION='bbuild'
-
-    if [[ "${1:0:1}" = "-" ]]; then
-        SECTION="${1:1}"
-        shift
-    fi
-
-    out:info "Seeking section [$SECTION] on all files."
-
-    print_from "$@"
-}
-
-print_from() {
-    # =================
-    # Process files
-
-    for file in "$@"; do
-        if [[ ! -f "$file" ]]; then
-            fullpath="$(searchpaths:file_from "$BBPATH" "$file")"
-            if [[ -n "$fullpath" ]]; then
-                file="$fullpath"
-            fi
-        fi
-
-        if [[ ! -f "$file" ]]; then
-            out:warn "No such file [$file]"
-            continue
-        fi
-
-        egrep '^##bash-libs:' "$file"
-
-        # Also print the tags for info
-        egrep '^#%bbtags' "$file"
-
-        autohelp:print "$SECTION" "$file"
+function debug:mode() {
+    local mode_switch
+    for mode_switch in "$@"; do
+        case "$mode_switch" in
+        output)
+            DEBUG_mode=true ;;
+        /output)
+            DEBUG_mode=false ;;
+        verbose)
+            set -x ;;
+        /verbose)
+            set +x ;;
+        esac
     done
 }
 
-runmain bashdoc main "$@"
+### debug:print MESSAGE Usage:bbuild
+# print a blue debug message to stderr
+# only prints if DEBUG_mode is set to "true"
+###/doc
+function debug:print {
+    [[ "$DEBUG_mode" = true ]] || return 0
+    echo "${CBBLU}DEBUG: $CBLU$*$CDEF" 1>&2
+}
+
+### debug:dump [MARKER] Usage:bbuild
+#
+# Pipe the data coming through stdin to stdout (as if it weren't there at all)
+#
+# If debug mode is on, *also* write the same data to stderr, each line preceded by MARKER
+#
+# Insert this function into pipes to see their output when in debugging mode
+#
+#   sed -r 's/linux|unix/*NIX/gi' myfile.txt | debug:dump | lprint
+#
+# Or use this to mask a command's output unless in debug mode
+#
+#   which binary 2>&1 | debug:dump >/dev/null
+#
+###/doc
+function debug:dump {
+    if [[ "$DEBUG_mode" = true ]]; then
+        local MARKER="${1:-DEBUG: }"; shift || :
+
+        cat - | sed -r "s/^/$MARKER/" | tee -a /dev/stderr
+    else
+        cat -
+    fi
+}
+
+### debug:break MESSAGE Usage:bbuild
+#
+# Add break points to a script
+#
+# Requires `DEBUG_mode` set to true
+#
+# When the script runs, the message is printed with a prompt, and execution pauses.
+#
+# Press return to continue execution.
+#
+# Type a variable name, with leading `$`, to dump it, e.g. `$myvar`
+#
+# Type a variable name, with leading `$`, follwoed by an assignment to change its value, e.g. `$myvar=new value`
+#  the new value will be seen by the script.
+#
+# Type 'env' to dump the current environment variables.
+#
+# Type `exit`, `quit` or `stop` to stop the program. If the breakpoint is in a subshell,
+#  execution from after the subshell will be resumed.
+#
+###/doc
+
+function debug:break {
+    [[ "$DEBUG_mode" = true ]] || return 0
+    local reply
+
+    while true; do
+        read -p "${CRED}BREAKPOINT: $* >$CDEF " reply
+        if [[ "$reply" =~ quit|exit|stop ]]; then
+            echo "${CBRED}ABORT${CDEF}" >&2
+            exit 127
+
+        elif [[ "$reply" = env ]]; then
+            env |sed 's//^[/g' |debug:dump "--- "
+
+        elif [[ "$reply" =~ ^\$ ]]; then
+            debug:_break_dump "${reply:1}" || :
+
+        elif [[ -z "$reply" ]]; then
+            return 0
+        else
+            debug:print "'quit','exit' or 'stop' to abort; '\$varname' to see a variable's contents; '\$varname=new value' to assign a new value for run time; <Enter> to continue"
+        fi
+    done
+}
+
+debug:_break_dump() {
+    local inspectable="$1"
+    local varname="$1"
+    local varval
+
+    if [[ "$inspectable" =~ = ]]; then
+        varname="${inspectable%%=*}"
+        varval="${inspectable#*=}"
+    fi
+
+    [[ "$varname" =~ $PAT_cvar ]] || {
+        debug:print "${CRED}Invalid var name '$varname'"
+        return 1
+    }
+
+    declare -n inspect="$varname"
+
+    if [[ "$inspectable" =~ = ]]; then
+        inspect="$varval"
+    else
+        echo "$inspect"
+    fi
+}
+
+removebuilt() {
+    rm "$BUILTSCR" "$BUILDMESSAGES"
+}
+
+rewrite_shebang() {
+    sed '1 s/bbrun/bash/g' -i "$BUILTSCR"
+}
+
+check_build_failure() {
+    if [[ "$1" != 0 ]]; then
+        echo -n "$CRED"
+        cat "$BUILDMESSAGES"
+        echo -n "$CDEF"
+
+        exit 1
+    fi
+}
+
+bbrun:main() {
+    . <(args:use:local bbscript -- "$@") ; 
+    local tempscr thisname
+
+    # Use absolute path so that built script is callable predictably
+    thisname="$(abspath:path "$bbscript")"
+    BUILTSCR="$(mktemp "${thisname}-XXXX")"
+    BUILDMESSAGES="$(mktemp)"
+
+    debug:print "Building dynamically | BBPATH => $BBPATH"
+
+    bbuild "$bbscript" "$BUILTSCR" &> "$BUILDMESSAGES"
+    BUILDRESULT=$?
+
+    trap removebuilt exit
+    check_build_failure "$BUILDRESULT"
+
+
+    rewrite_shebang
+
+    "$BUILTSCR" "$@"
+}
+
+bbrun:main "$@"
