Re-work the installer, pre-built executables included, do not systematically include libs

diff --git a/bin/bbuild b/bin/bbuild
--- a/bin/bbuild
+++ b/bin/bbuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION_NUM=5.3
+VERSION_NUM=5.4
 VERSION_NOTE="See https://github.com/taikedz/bbuild"
 
 [[ "$*" = --version ]] && {
@@ -74,42 +74,19 @@ VERSION_NOTE="See https://github.com/taikedz/bbuild"
 #   This allows simply running "bbuild" to build specified project scripts
 #
 # 	BBFILES=(src/script1 src/script2 libs/support_script)
+# 
+#
+# Syntax post-processing
+# ----------------------
+#
+# Bash Builder 5.2+ provides a post-processing utiltiy enabling extra syntax macros that
+# can help write easier-to-maintain code.
+#
+# Run bbuild `--help syntax` for more information
 #
 ###/doc
 
-##bash-libs: out.sh @ %COMMITHASH%
-
-##bash-libs: colours.sh @ %COMMITHASH%
-
-### Colours for bash Usage:bbuild
-# A series of colour flags for use in outputs.
-#
-# Example:
-# 	
-# 	echo -e "${CRED}Some red text ${CBBLU} some blue text $CDEF some text in the terminal's default colour")
-#
-# Requires processing of escape characters.
-#
-# Colours available:
-#
-# CRED, CBRED, HLRED -- red, bold red, highlight red
-# CGRN, CBGRN, HLGRN -- green, bold green, highlight green
-# CYEL, CBYEL, HLYEL -- yellow, bold yellow, highlight yellow
-# CBLU, CBBLU, HLBLU -- blue, bold blue, highlight blue
-# CPUR, CBPUR, HLPUR -- purple, bold purple, highlight purple
-# CTEA, CBTEA, HLTEA -- teal, bold teal, highlight teal
-#
-# CDEF -- switches to the terminal default
-# CUNL -- add underline
-#
-# Note that highlight and underline must be applied or re-applied after specifying a colour.
-#
-# If the session is detected as being in a pipe, colours will be turned off.
-#   You can override this by calling `colours:check --color=always` at the start of your script
-#
-###/doc
-
-##bash-libs: tty.sh @ %COMMITHASH%
+##bash-libs: tty.sh @ bf310b32 (1.4.1)
 
 tty:is_ssh() {
     [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
@@ -119,10 +96,65 @@ tty:is_pipe() {
     [[ ! -t 1 ]]
 }
 
-### colours:check ARGS Usage:bbuild
+##bash-libs: colours.sh @ bf310b32 (1.4.1)
+
+### Colours for terminal Usage:bbuild
+# A series of shorthand colour flags for use in outputs, and functions to set your own flags.
+#
+# Not all terminals support all colours or modifiers.
+#
+# Example:
+# 	
+# 	echo "${CRED}Some red text ${CBBLU} some blue text. $CDEF Some text in the terminal's default colour")
+#
+# Preconfigured colours available:
+#
+# CRED, CBRED, HLRED -- red, bright red, highlight red
+# CGRN, CBGRN, HLGRN -- green, bright green, highlight green
+# CYEL, CBYEL, HLYEL -- yellow, bright yellow, highlight yellow
+# CBLU, CBBLU, HLBLU -- blue, bright blue, highlight blue
+# CPUR, CBPUR, HLPUR -- purple, bright purple, highlight purple
+# CTEA, CBTEA, HLTEA -- teal, bright teal, highlight teal
+# CBLA, CBBLA, HLBLA -- black, bright red, highlight red
+# CWHI, CBWHI, HLWHI -- white, bright red, highlight red
+#
+# Modifiers available:
+#
+# CBON - activate bright
+# CDON - activate dim
+# ULON - activate underline
+# RVON - activate reverse (switch foreground and background)
+# SKON - activate strikethrough
+# 
+# Resets available:
+#
+# CNORM -- turn off bright or dim, without affecting other modifiers
+# ULOFF -- turn off highlighting
+# RVOFF -- turn off inverse
+# SKOFF -- turn off strikethrough
+# HLOFF -- turn off highlight
+#
+# CDEF -- turn off all colours and modifiers(switches to the terminal default)
+#
+# Note that highlight and underline must be applied or re-applied after specifying a colour.
+#
+# If the session is detected as being in a pipe, colours will be turned off.
+#   You can override this by calling `colours:check --color=always` at the start of your script
+#
+###/doc
+
+### colours:check ARGS ... Usage:bbuild
 #
 # Check the args to see if there's a `--color=always` or `--color=never`
 #   and reload the colours appropriately
+#
+#   main() {
+#       colours:check "$@"
+#
+#       echo "${CGRN}Green only in tty or if --colours=always !${CDEF}"
+#   }
+#
+#   main "$@"
 #
 ###/doc
 colours:check() {
@@ -136,6 +168,74 @@ colours:check() {
     return 0
 }
 
+### colours:set CODE Usage:bbuild
+# Set an explicit colour code - e.g.
+#
+#   echo "$(colours:set "33;2")Dim yellow text${CDEF}"
+#
+# See SGR Colours definitions
+#   <https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters>
+###/doc
+colours:set() {
+    # We use `echo -e` here rather than directly embedding a binary character
+    if [[ "$COLOURS_ON" = false ]]; then
+        return 0
+    else
+        echo -e "\033[${1}m"
+    fi
+}
+
+colours:define() {
+
+    # Shorthand colours
+
+    export CBLA="$(colours:set "30")"
+    export CRED="$(colours:set "31")"
+    export CGRN="$(colours:set "32")"
+    export CYEL="$(colours:set "33")"
+    export CBLU="$(colours:set "34")"
+    export CPUR="$(colours:set "35")"
+    export CTEA="$(colours:set "36")"
+    export CWHI="$(colours:set "37")"
+
+    export CBBLA="$(colours:set "1;30")"
+    export CBRED="$(colours:set "1;31")"
+    export CBGRN="$(colours:set "1;32")"
+    export CBYEL="$(colours:set "1;33")"
+    export CBBLU="$(colours:set "1;34")"
+    export CBPUR="$(colours:set "1;35")"
+    export CBTEA="$(colours:set "1;36")"
+    export CBWHI="$(colours:set "1;37")"
+
+    export HLBLA="$(colours:set "40")"
+    export HLRED="$(colours:set "41")"
+    export HLGRN="$(colours:set "42")"
+    export HLYEL="$(colours:set "43")"
+    export HLBLU="$(colours:set "44")"
+    export HLPUR="$(colours:set "45")"
+    export HLTEA="$(colours:set "46")"
+    export HLWHI="$(colours:set "47")"
+
+    # Modifiers
+    
+    export CBON="$(colours:set "1")"
+    export CDON="$(colours:set "2")"
+    export ULON="$(colours:set "4")"
+    export RVON="$(colours:set "7")"
+    export SKON="$(colours:set "9")"
+
+    # Resets
+
+    export CBNRM="$(colours:set "22")"
+    export HLOFF="$(colours:set "49")"
+    export ULOFF="$(colours:set "24")"
+    export RVOFF="$(colours:set "27")"
+    export SKOFF="$(colours:set "29")"
+
+    export CDEF="$(colours:set "0")"
+
+}
+
 colours:auto() {
     if tty:is_pipe ; then
         COLOURS_ON=false
@@ -147,61 +247,9 @@ colours:auto() {
     return 0
 }
 
-colours:define() {
-    if [[ "$COLOURS_ON" = false ]]; then
-
-        export CRED=''
-        export CGRN=''
-        export CYEL=''
-        export CBLU=''
-        export CPUR=''
-        export CTEA=''
-
-        export CBRED=''
-        export CBGRN=''
-        export CBYEL=''
-        export CBBLU=''
-        export CBPUR=''
-        export CBTEA=''
-
-        export HLRED=''
-        export HLGRN=''
-        export HLYEL=''
-        export HLBLU=''
-        export HLPUR=''
-        export HLTEA=''
-
-        export CDEF=''
-
-    else
-
-        export CRED=$(echo -e "\033[0;31m")
-        export CGRN=$(echo -e "\033[0;32m")
-        export CYEL=$(echo -e "\033[0;33m")
-        export CBLU=$(echo -e "\033[0;34m")
-        export CPUR=$(echo -e "\033[0;35m")
-        export CTEA=$(echo -e "\033[0;36m")
-
-        export CBRED=$(echo -e "\033[1;31m")
-        export CBGRN=$(echo -e "\033[1;32m")
-        export CBYEL=$(echo -e "\033[1;33m")
-        export CBBLU=$(echo -e "\033[1;34m")
-        export CBPUR=$(echo -e "\033[1;35m")
-        export CBTEA=$(echo -e "\033[1;36m")
-
-        export HLRED=$(echo -e "\033[41m")
-        export HLGRN=$(echo -e "\033[42m")
-        export HLYEL=$(echo -e "\033[43m")
-        export HLBLU=$(echo -e "\033[44m")
-        export HLPUR=$(echo -e "\033[45m")
-        export HLTEA=$(echo -e "\033[46m")
-
-        export CDEF=$(echo -e "\033[0m")
-
-    fi
-}
-
 colours:auto
+
+##bash-libs: out.sh @ bf310b32 (1.4.1)
 
 ### Console output handlers Usage:bbuild
 #
@@ -289,7 +337,7 @@ function out:error {
     echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
 }
 
-##bash-libs: autohelp.sh @ %COMMITHASH%
+##bash-libs: autohelp.sh @ bf310b32 (1.4.1)
 
 ### Autohelp Usage:bbuild
 #
@@ -470,9 +518,7 @@ autohelp:check_section() {
         fi
     done
 }
-##bash-libs: args.sh @ %COMMITHASH%
-
-##bash-libs: patterns.sh @ %COMMITHASH%
+##bash-libs: patterns.sh @ bf310b32 (1.4.1)
 
 ### Useful patterns Usage:bbuild
 #
@@ -496,6 +542,8 @@ export PAT_num='^[0-9]+$'
 export PAT_cvar='^[a-zA-Z_][a-zA-Z0-9_]*$'
 export PAT_filename='^[a-zA-Z0-9_.-]$'
 export PAT_email="$PAT_filename@$PAT_filename.$PAT_cvar"
+
+##bash-libs: args.sh @ bf310b32 (1.4.1)
 
 ### args Usage:bbuild
 #
@@ -642,16 +690,20 @@ args:after() {
 #
 # If not enough argument values are found, the first named variable that failed to be assigned is printed as error
 #
+# ARGNAMES prefixed with '?' do not trigger an error
+#
 # Example:
 #
 #   #%include out.sh
 #   #%include args.sh
 #
 #   get_parameters() {
-#       . <(args:use INFILE OUTFILE -- "$@")
+#       . <(args:use INFILE OUTFILE ?comment -- "$@")
 #
 #       [[ -f "$INFILE" ]]  || out:fail "Input file '$INFILE' does not exist"
 #       [[ -f "$OUTFILE" ]] || out:fail "Output file '$OUTFILE' does not exist"
+#
+#       [[ -z "$comment" ]] || echo "Note: $comment"
 #   }
 #
 #   main() {
@@ -664,17 +716,24 @@ args:after() {
 #
 ###/doc
 args:use() {
-    local argname arglist # TODO - consume meta args
+    local argname arglist undef_f
     arglist=(:)
     for argname in "$@"; do
         [[ "$argname" != -- ]] || break
-        [[ "$argname" =~ ^[0-9a-zA-Z_]+$ ]] || out:fail "Internal: Not a valid argument name '$argname'"
+        [[ "$argname" =~ ^\??[0-9a-zA-Z_]+$ ]] || out:fail "Internal: Not a valid argument name '$argname'"
 
         arglist+=("$argname")
     done
 
     for argname in "${arglist[@]:1}"; do
-        echo "$ARGSLIB_scope $argname=\"\${1:-}\"; shift || out:fail \"Internal : could not get '$argname'\""
+        if [[ "$argname" =~ ^\? ]]; then
+            argname="${argname:1}"
+            undef_f=":"
+        else
+            undef_f="out:fail \"Internal : could not get '$argname'\""
+        fi
+
+        echo "$ARGSLIB_scope $argname=\"\${1:-}\"; shift || $undef_f"
     done
 }
 
@@ -708,6 +767,8 @@ args:use() {
 args:use:local() {
     ARGSLIB_scope=local args:use "$@"
 }
+
+##bash-libs: debug.sh @ bf310b32 (1.4.1)
 
 ### Debug lib Usage:bbuild
 #
@@ -808,15 +869,8 @@ function debug:break {
         echo "${CBRED}ABORT${CDEF}"
     fi
 }
-##bash-libs: includefile2.sh @ %COMMITHASH%
 
-### File Inclusion Usage:bbuild
-# Library for including (once) or inserting (any time called) external files ontents
-# based on developer-defined tokens
-##/doc
-
-##bash-libs: searchpaths.sh @ %COMMITHASH%
-
+##bash-libs: searchpaths.sh @ bf310b32 (1.4.1)
 
 # FIXME - set function signature in head of help
 ### searchpaths:file_from PATHDEF FILE Usage:bbuild
@@ -851,6 +905,13 @@ function searchpaths:file_from {
     done
     return 1
 }
+
+##bash-libs: includefile2.sh @ bf310b32 (1.4.1)
+
+### File Inclusion Usage:bbuild
+# Library for including (once) or inserting (any time called) external files ontents
+# based on developer-defined tokens
+##/doc
 
 includefile:reset_tracker() {
     INCLUDEFILE_tracker=""
@@ -957,7 +1018,7 @@ includefile:_cat_once() {
 includefile:cleanup() {
     rm ./._include-*
 }
-##bash-libs: bincheck.sh @ %COMMITHASH%
+##bash-libs: bincheck.sh @ bf310b32 (1.4.1)
 
 ### bincheck:get COMMANDS ... Usage:bbuild
 #
@@ -1029,79 +1090,34 @@ bincheck:path() {
     
     } || echo "$binname"
 }
-### Syntax Post-processing Usage:help
+
+### Syntax Post-processing Usage:syntax
 #
 # Bash Builder adds some post-processing to built files
-# as an option, to allow some extra features.
+# to allow some extra features.
 #
-# You can opt to switch on all syntax post-processing
-# subfeatures ("syntax extensions"), or individual ones
+# It is active by default ; you can set an environment variable
+# `BBSYNTAX=off` to prevent it from activating.
 #
 ###/doc
 
 # TODO - there are several array-related shortcuts to add
 # * transparent handling of serialization
 #   * though this may be rendered less relevant with strict mode
-# * associative arrays
 
 bbuild:syntax_post() {
     [[ "${BBSYNTAX:-}" != off ]] || return 0
 
-	local target="${1:-}"; shift || :
+	local target="${1:-}"; shift || out:fail "No syntax post-processing target supplied !"
 	
-	bbuild:syntax:expand_local "$target"
-	bbuild:syntax:expand_arg1 "$target"
     bbuild:syntax:expand_function_signatures "$target"
+    bbuild:syntax:dot_arrays "$target"
 }
 
-### expandarg1 Usage:bbuild
+### Function signature expansion Usage:syntax
 #
-# An option which allows safe assignment of the first argument, and
-# forces a shift. The shift itself may error, allowing it to be caught.
-#
-# 	You write ==>   ="${1:-}"; shift 
-#
-# 	You get   ==>   ="${1:-}"; shift
-#
-# 	Example :
-#
-# 		myfunc() {
-# 			person="${1:-}"; shift || out:fail "person not specified"
-# 			message="${1:-}"; shift || out:fail "message not specified"
-#
-# 			echo "Hello $person : $message"
-# 		}
-#
-##/doc
-bbuild:syntax:expand_arg1() {
-	# adjacent quotes prevent this code from mangling itself
-	sed -r 's/=\$''%1\s*/="${1:-}"; shift /g' -i "$1"
-}
-
-### expandlocal Usage:bbuild
-#
-# An option which allows quickly defining a local variable
-#
-# 	You write ===>   $%myvar=
-#
-# 	You get   ===>   local myvar=
-#
-# 	Example:
-#
-# 	    myfunc() {
-# 	        # declare a local variable person
-# 	        $%person="$1"
-#
-# 	        echo "Hello $person"
-# 	    }
-###/doc
-bbuild:syntax:expand_local() {
-	sed -r 's/^(\s*)\$''%([a-zA-Z0-9_]+)=/\1local \2=/g' -i "$1"
-}
-
-### expandfsig Usage:bbuild
-#
-# An option to use a function's signature to declare local variables
+# An option to use a function's signature to declare local variables.
+# Requires your script to include `args.sh`
 #
 # NOTE: function names must match the following regex:
 #   ^[a-zA-Z0-9_:.-]+$
@@ -1119,6 +1135,67 @@ bbuild:syntax:expand_local() {
 ###/doc
 bbuild:syntax:expand_function_signatures() {
     sed -r 's/^(\s*)\$''%function\s*([a-zA-Z0-9_:.-]+)\(([^)]+?)\)\s+\{''/''\1\2() {\n\1    . <(args:use:local \3 -- "$@") ; ''/' -i "$1"
+}
+
+### Dot notation for associative arrays Usage:syntax
+#
+# Access a data map array via dot notation:
+#
+# Dot notation is identified by use of `$%.`
+#
+# Assignment is done by using an `=` sign immediately after the dot notation
+#
+#   object[property1]=value
+#   object[property2]=stuff
+#
+# Value printing is done by not including an equality sign
+#
+#   echo "${object[property1]}"
+#
+# An iterable series of values can be printed using `@` notation
+#
+#   process_values "${object[@]}"
+#
+# The values themselves, on one line, can be printed using `*` notation
+#
+#   echo "${object[*]}"
+#
+###/doc
+bbuild:syntax:dot_arrays() {
+    local transforms
+    transforms=(
+        # object[property]=     --> object[property]=
+        # object[$placeholder]= --> object[$placeholder]=
+        -e 's/\$%\.([a-zA-Z0-9_]+)\.([$a-zA-Z0-9_]+)=/\1[\2]=/g'
+
+        # ${object[property]}     --> ${object[property]}
+        # ${object[$placeholder]} --> ${object[$placeholder]}
+        -e 's/\$%\.([a-zA-Z0-9_]+)\.([$a-zA-Z0-9_]+)/${\1[\2]}/g'
+
+        # ${!object[@]} --> ${!object[@]}
+        -e 's/\$%\.([a-zA-Z0-9_]+)\[\!\]/${!\1[@]}/g'
+
+        # ${object[@]} --> ${object[@]}
+        -e 's/\$%\.([a-zA-Z0-9_]+)\[@\]/${\1[@]}/g'
+
+        # ${object[*]} --> ${object[*]}
+        -e 's/\$%\.([a-zA-Z0-9_]+)\[\*\]/${\1[*]}/g'
+
+        # ${object[<some variable or string>]} --> ${object[<the same>]}
+        -e 's/\$%\.([a-zA-Z0-9_]+)\[([^]]+)\]/${\1[\2]}/g'
+
+        # declare -A object --> declare -A object
+        -e 's/local\s+\$%\.([a-zA-Z0-9_]+)/declare -A \1/g'
+
+        # declare -Ag object --> declare -Ag object
+        -e 's/\$%\.([a-zA-Z0-9_]+)/declare -Ag \1/g'
+    )
+
+    sed -r "${transforms[@]}" -i "$1"
+
+    if grep "\$%\." "$1"|grep -vP '^\s*#' ; then
+        out:fail "--- Some dot-array syntax did not convert ---"
+    fi
 }
 
 setup_build_dir() {
@@ -1243,6 +1320,10 @@ build_files_list() {
 }
 
 main() {
+    if [[ "$*" =~ "--help syntax" ]]; then
+        autohelp:print syntax
+        exit 0
+    fi
     autohelp:check "$@"
 
     BBUILD_ENV_FILE=./bbuildrc
