use newer libs with inclusion-fix

diff --git a/bin/bbuild b/bin/bbuild
--- a/bin/bbuild
+++ b/bin/bbuild
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-VERSION_NUM=6.0.2
+VERSION_NUM=6.0.3
 VERSION_NOTE="See https://github.com/taikedz/bbuild"
 
 [[ "$*" = --version ]] && {
@@ -51,7 +51,7 @@ VERSION_NOTE="See https://github.com/taikedz/bbuild"
 #
 ###/doc
 
-##bash-libs: safe.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: safe.sh @ 9d200ab4 (2.0.6)
 
 ### Safe mode Usage:bbuild
 #
@@ -66,26 +66,22 @@ VERSION_NOTE="See https://github.com/taikedz/bbuild"
 # Splitting over spaces
 # ---------------------
 #
-# You can also switch space splitting on or off (normal bash default is 'on')
+# Using bash's defaults, array assignments split over any whitespace.
 #
-# Given a function `foo()` that returns multiple lines, which may each have spaces in them, use safe splitting to return each item into an array as its own item, without splitting over spaces.
+# Using safe mode, arrays only split over newlines, not over spaces.
 #
-#   safe:space-split off
-#   mylist=(foo)
-#   safe:space-split on
+# Return to default unsafe behaviour using `safe:space-split on`
 #
-# Having space splitting on causes statements like `echo "$*"` to print each argument on its own line.
+# Reactivate safe recommendation using `safe:space-split off`
 #
 # Globs
 # -------
 #
 # In safe mode, glob expansion like `ls .config/*` is turned off by default.
 #
-# You can turn glob expansion on and off with `safe:glob on` or `safe:glob off`
+# You can turn glob expansion on with `safe:glob on`, and off with `safe:glob off`
 #
 ###/doc
-
-set -eufo pipefail
 
 safe:space-split() {
     case "$1" in
@@ -114,7 +110,10 @@ safe:glob() {
         ;;
     esac
 }
-##bash-libs: tty.sh @ 6421286a-uncommitted (2.0.1)
+
+set -eufo pipefail
+safe:space-split off
+##bash-libs: tty.sh @ 9d200ab4 (2.0.6)
 
 tty:is_ssh() {
     [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
@@ -124,7 +123,7 @@ tty:is_pipe() {
     [[ ! -t 1 ]]
 }
 
-##bash-libs: colours.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: colours.sh @ 9d200ab4 (2.0.6)
 
 ### Colours for terminal Usage:bbuild
 # A series of shorthand colour flags for use in outputs, and functions to set your own flags.
@@ -277,7 +276,7 @@ colours:auto() {
 
 colours:auto
 
-##bash-libs: out.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: out.sh @ 9d200ab4 (2.0.6)
 
 ### Console output handlers Usage:bbuild
 #
@@ -364,7 +363,8 @@ function out:fail {
 function out:error {
     echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
 }
-##bash-libs: syntax-extensions.sh @ 6421286a-uncommitted (2.0.1)
+
+##bash-libs: syntax-extensions.sh @ 9d200ab4 (2.0.6)
 
 ### Syntax Extensions Usage:syntax
 #
@@ -426,7 +426,7 @@ syntax-extensions:use() {
     argidx=1
     while [[ "$argidx" -lt "${#arglist[@]}" ]]; do
         argname="${arglist[$argidx]}"
-        failmsg="\"Internal : could not get '$argname' in function arguments\""
+        failmsg="\"Internal: could not get '$argname' in function arguments\""
         posfailmsg="Internal: positional argument '$argname' encountered after optional argument(s)"
 
         if [[ "$argname" =~ ^\? ]]; then
@@ -435,6 +435,7 @@ syntax-extensions:use() {
 
         elif [[ "$argname" =~ ^\* ]]; then
             [[ "$pos_ok" != false ]] || out:fail "$posfailmsg"
+            echo "[[ '${argname:1}' != \"$argone\" ]] || out:fail \"Internal: Local name [$argname] equals upstream [$argone]. Rename [$argname] (suggestion: [*p_${argname:1}])\""
             echo "declare -n${dec_scope} ${argname:1}=$argone; shift || out:fail $failmsg"
 
         else
@@ -477,7 +478,7 @@ args:use:local() {
     syntax-extensions:use:local "$@"
 }
 
-##bash-libs: autohelp.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: autohelp.sh @ 9d200ab4 (2.0.6)
 
 ### Autohelp Usage:bbuild
 #
@@ -675,7 +676,7 @@ autohelp:check:section() {
         fi
     done
 }
-##bash-libs: patterns.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: patterns.sh @ 9d200ab4 (2.0.6)
 
 ### Useful patterns Usage:bbuild
 #
@@ -700,7 +701,7 @@ export PAT_cvar='^[a-zA-Z_][a-zA-Z0-9_]*$'
 export PAT_filename='^[a-zA-Z0-9_.-]$'
 export PAT_email="$PAT_filename@$PAT_filename.$PAT_cvar"
 
-##bash-libs: args.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: args.sh @ 9d200ab4 (2.0.6)
 
 ### args Usage:bbuild
 #
@@ -841,7 +842,7 @@ args:after() {
     RETARR_ARGSAFTER=("$@")
 }
 
-##bash-libs: debug.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: debug.sh @ 9d200ab4 (2.0.6)
 
 ### Debug lib Usage:bbuild
 #
@@ -988,7 +989,7 @@ debug:_break_dump() {
     fi
 }
 
-##bash-libs: searchpaths.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: searchpaths.sh @ 9d200ab4 (2.0.6)
 
 # FIXME - set function signature in head of help
 ### searchpaths:file_from PATHDEF FILE Usage:bbuild
@@ -1014,6 +1015,9 @@ function searchpaths:file_from {
     local PATHS="$1"; shift || :
     local FILE="$1"; shift || :
 
+    local oldIFS="$IFS"
+    IFS=$' \t\n'
+
     for path in $(echo "$PATHS"|tr ':' ' '); do
         local fpath="$path/$FILE"
         if [[ -f "$fpath" ]]; then
@@ -1021,15 +1025,17 @@ function searchpaths:file_from {
             return 0
         fi
     done
+
+    IFS="$oldIFS"
     return 1
 }
 
-##bash-libs: includefile2.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: includefile2.sh @ 9d200ab4 (2.0.6)
 
 ### File Inclusion Usage:bbuild
 # Library for including (once) or inserting (any time called) external files ontents
 # based on developer-defined tokens
-##/doc
+###/doc
 
 includefile:reset_tracker() {
     INCLUDEFILE_tracker=""
@@ -1041,8 +1047,8 @@ includefile:reset_tracker() {
 # Writes fully included result to stdout
 #
 # set INCLUDEFILE_token string to define the token which, at the begining of a line
-#  declares a list of files to include
-# set INCLUDEFILE_paths colon-delimited string to a search pth from which to find scripts to source
+#  declares a single file to include
+# set INCLUDEFILE_paths colon-delimited string to a search path from which to find scripts to source
 ###/doc
 includefile:process() {
     local target
@@ -1070,10 +1076,10 @@ includefile:process() {
 }
 
 ### includefile:_process_first_inclusion TARGET Usage:internal
-# Find the first onclusion line, and include its targets
+# Find the first onclusion line, and include its target in the output
 #
-# returns 0 on successful inclusions
-# returns 1 on issues with inclusions
+# returns 0 on successful inclusion
+# returns 1 on issues with inclusion
 ###/doc
 includefile:_process_first_inclusion() {
     local fd_target="$1"; shift
@@ -1081,10 +1087,10 @@ includefile:_process_first_inclusion() {
     cat "$fd_target" > "$target"
 
     local pos=$(includefile:_get_inclusion_line_pos "$target")
-    local inctokens=($(includefile:_get_inclusion_line_string "$target"))
+    local inctoken="$(includefile:_get_inclusion_line_string "$target")"
 
     head -n $((pos - 1)) "$target"
-    includefile:_cat_once "${inctokens[@]:1}" || return 1
+    includefile:_cat_once "$inctoken" || return 1
     tail -n +$((pos + 1)) "$target"
 
     rm "$target"
@@ -1101,7 +1107,7 @@ includefile:_get_inclusion_line_pos() {
 includefile:_get_inclusion_line_string() {
     local targetfile="$1"; shift
 
-    grep -P "^$INCLUDEFILE_token" "$targetfile" | head -n 1 
+    grep -P "^$INCLUDEFILE_token" "$targetfile" | head -n 1 | sed -r -e "s^$INCLUDEFILE_token" -e 's/^\s+|\s+$//g'
 }
 
 includefile:_has_inclusion_line() {
@@ -1111,32 +1117,31 @@ includefile:_has_inclusion_line() {
 }
 
 includefile:_cat_once() {
-    local item
+    . <(args:use:local item -- "$@") ; 
     local fullpath
     local b64t
-    for item in "$@"; do
-        [[ -n "$item" ]] || continue
 
-        fullpath="$(searchpaths:file_from "$INCLUDEFILE_paths" "$item")"
-        if [[ -z "$fullpath" ]]; then
-            INCLUDEFILE_failed="$item"
-            return 1
-        fi
-        
-        b64t=";$(echo "$fullpath" | base64 -w 0);"
-        if [[  "$INCLUDEFILE_tracker" =~ "$b64t" ]]; then
-            continue
-        fi
+    [[ -n "$item" ]] || return 1
 
-        export INCLUDEFILE_tracker="$INCLUDEFILE_tracker $b64t"
-        cat "$fullpath"
-    done
+    fullpath="$(searchpaths:file_from "$INCLUDEFILE_paths" "$item")"
+    if [[ -z "$fullpath" ]]; then
+        INCLUDEFILE_failed="$item"
+        return 1
+    fi
+    
+    b64t=";$(echo "$fullpath" | base64 -w 0);"
+    if [[  "$INCLUDEFILE_tracker" =~ "$b64t" ]]; then
+        return
+    fi
+
+    export INCLUDEFILE_tracker="$INCLUDEFILE_tracker $b64t"
+    cat "$fullpath"
 }
 
 includefile:cleanup() {
     rm ./._include-*
 }
-##bash-libs: bincheck.sh @ 6421286a-uncommitted (2.0.1)
+##bash-libs: bincheck.sh @ 9d200ab4 (2.0.6)
 
 ### bincheck:get COMMANDS ... Usage:bbuild
 #
