Changed command structure, removed bbuilrc support.
Ready for release.

diff --git a/bin/tarshc b/bin/tarshc
--- a/bin/tarshc
+++ b/bin/tarshc
@@ -6,189 +6,7 @@
 #
 ###/doc
 
-
-##bash-libs: autohelp.sh @ bf310b32 (1.4.1)
-
-### Autohelp Usage:bbuild
-#
-# Autohelp provides some simple facilities for defining help as comments in your code.
-# It provides several functions for printing specially formatted comment sections.
-#
-# Write your help as documentation comments in your script
-#
-# To output a named section from your script, or a file, call the
-# `autohelp:print` function and it will print the help documentation
-# in the current script, or specified file, to stdout
-#
-# A help comment looks like this:
-#
-#    ### <title> Usage:help
-#    #
-#    # <some content>
-#    #
-#    # end with "###/doc" on its own line (whitespaces before
-#    # and after are OK)
-#    #
-#    ###/doc
-#
-# It can then be printed from the same script by simply calling
-#
-#   autohelp:print
-#
-# You can print a different section by specifying a different name
-#
-# 	autohelp:print section2
-#
-# > This would print a section defined in this way:
-#
-# 	### Some title Usage:section2
-# 	# <some content>
-# 	###/doc
-#
-# You can set a different comment character by setting the 'HELPCHAR' environment variable.
-# Typically, you might want to print comments you set in a INI config file, for example
-#
-# 	HELPCHAR=";" autohelp:print help config-file.ini
-# 
-# Which would then find comments defined like this in `config-file.ini`:
-#
-#   ;;; Main config Usage:help
-#   ; Help comments in a config file
-#   ; may start with a different comment character
-#   ;;;/doc
-#
-#
-#
-# Example usage in a multi-function script:
-#
-#   #!/bin/bash
-#
-#   ### Main help Usage:help
-#   # The main help
-#   ###/doc
-#
-#   ### Feature One Usage:feature_1
-#   # Help text for the first feature
-#   ###/doc
-#
-#   feature1() {
-#       autohelp:check_section feature_1 "$@"
-#       echo "Feature I"
-#   }
-#
-#   ### Feature Two Usage:feature_2
-#   # Help text for the second feature
-#   ###/doc
-#
-#   feature2() {
-#       autohelp:check_section feature_2 "$@"
-#       echo "Feature II"
-#   }
-#
-#   main() {
-#       if [[ -z "$*" ]]; then
-#           ### No command specified Usage:no-command
-#           #No command specified. Try running with `--help`
-#           ###/doc
-#
-#           autohelp:print no-command
-#           exit 1
-#       fi
-#
-#       case "$1" in
-#       feature1|feature2)
-#           "$1" "$@"            # Pass the global script arguments through
-#           ;;
-#       *)
-#           autohelp:check "$@"  # Check if main help was asked for, if so, exits
-#
-#           # Main help not requested, return error
-#           echo "Unknown feature"
-#           exit 1
-#           ;;
-#       esac
-#   }
-#
-#   main "$@"
-#
-###/doc
-
-### autohelp:print [ SECTION [FILE] ] Usage:bbuild
-# Print the specified section, in the specified file.
-#
-# If no file is specified, prints for current script file.
-# If no section is specified, defaults to "help"
-###/doc
-
-HELPCHAR='#'
-
-autohelp:print() {
-    local input_line
-    local section_string="${1:-}"; shift || :
-    local target_file="${1:-}"; shift || :
-    [[ -n "$section_string" ]] || section_string=help
-    [[ -n "$target_file" ]] || target_file="$0"
-
-    #echo -e "\n$(basename "$target_file")\n===\n"
-    local sec_start='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s+(.+?)\s+Usage:'"$section_string"'\s*$'
-    local sec_end='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s*/doc\s*$'
-    local in_section=false
-
-    while read input_line; do
-        if [[ "$input_line" =~ $sec_start ]]; then
-            in_section=true
-            echo -e "\n${BASH_REMATCH[1]}\n======="
-
-        elif [[ "$in_section" = true ]]; then
-            if [[ "$input_line" =~ $sec_end ]]; then
-                in_section=false
-            else
-                echo "$input_line" | sed -r "s/^\s*$HELPCHAR/ /;s/^  (\S)/\1/"
-            fi
-        fi
-    done < "$target_file"
-
-    if [[ "$in_section" = true ]]; then
-            out:fail "Non-terminated help block."
-    fi
-}
-
-### autohelp:paged Usage:bbuild
-#
-# Display the help in the pager defined in the PAGER environment variable
-#
-###/doc
-autohelp:paged() {
-    : ${PAGER=less}
-    autohelp:print "$@" | $PAGER
-}
-
-### autohelp:check ARGS ... Usage:bbuild
-#
-# Automatically print "help" sections and exit, if "--help" is detected in arguments
-#
-###/doc
-autohelp:check() {
-    autohelp:check_section "help" "$@"
-}
-
-### autohelp:check_section SECTION ARGS ... Usage:bbuild
-# Automatically print documentation for named section and exit, if "--help" is detected in arguments
-#
-###/doc
-autohelp:check_section() {
-    local section arg
-    section="${1:-}"; shift || out:fail "No help section specified"
-
-    for arg in "$@"; do
-        if [[ "$arg" =~ --help ]]; then
-            cols="$(tput cols)"
-            autohelp:print "$section" | fold -w "$cols" -s || autohelp:print "$section"
-            exit 0
-        fi
-    done
-}
-##bash-libs: tty.sh @ bf310b32 (1.4.1)
+##bash-libs: tty.sh @ 69724119 (2.0)
 
 tty:is_ssh() {
     [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
@@ -198,7 +16,7 @@ tty:is_pipe() {
     [[ ! -t 1 ]]
 }
 
-##bash-libs: colours.sh @ bf310b32 (1.4.1)
+##bash-libs: colours.sh @ 69724119 (2.0)
 
 ### Colours for terminal Usage:bbuild
 # A series of shorthand colour flags for use in outputs, and functions to set your own flags.
@@ -351,7 +169,7 @@ colours:auto() {
 
 colours:auto
 
-##bash-libs: out.sh @ bf310b32 (1.4.1)
+##bash-libs: out.sh @ 69724119 (2.0)
 
 ### Console output handlers Usage:bbuild
 #
@@ -438,8 +256,319 @@ function out:fail {
 function out:error {
     echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
 }
+##bash-libs: syntax-extensions.sh @ 69724119 (2.0)
 
-##bash-libs: searchpaths.sh @ bf310b32 (1.4.1)
+### Syntax Extensions Usage:syntax
+#
+# Syntax extensions for bash-builder.
+#
+# You will need to import this library if you use Bash Builder's extended syntax macros.
+#
+# You should not however use the functions directly, but the extended syntax instead.
+#
+##/doc
+
+### syntax-extensions:use FUNCNAME ARGNAMES ... Usage:syntax
+#
+# Consume arguments into named global variables.
+#
+# If not enough argument values are found, the first named variable that failed to be assigned is printed as error
+#
+# ARGNAMES prefixed with '?' do not trigger an error
+#
+# Example:
+#
+#   #%include out.sh
+#   #%include syntax-extensions.sh
+#
+#   get_parameters() {
+#       . <(syntax-extensions:use get_parameters INFILE OUTFILE ?comment)
+#
+#       [[ -f "$INFILE" ]]  || out:fail "Input file '$INFILE' does not exist"
+#       [[ -f "$OUTFILE" ]] || out:fail "Output file '$OUTFILE' does not exist"
+#
+#       [[ -z "$comment" ]] || echo "Note: $comment"
+#   }
+#
+#   main() {
+#       get_parameters "$@"
+#
+#       echo "$INFILE will be converted to $OUTFILE"
+#   }
+#
+#   main "$@"
+#
+###/doc
+syntax-extensions:use() {
+    local argname arglist undef_f dec_scope argidx argone failmsg pos_ok
+    
+    dec_scope=""
+    [[ "${SYNTAXLIB_scope:-}" = local ]] || dec_scope=g
+    arglist=(:)
+    argone=\"\${1:-}\"
+    pos_ok=true
+    
+    for argname in "$@"; do
+        [[ "$argname" != -- ]] || break
+        [[ "$argname" =~ ^(\?|\*)?[0-9a-zA-Z_]+$ ]] || out:fail "Internal: Not a valid argument name '$argname'"
+
+        arglist+=("$argname")
+    done
+
+    argidx=1
+    while [[ "$argidx" -lt "${#arglist[@]}" ]]; do
+        argname="${arglist[$argidx]}"
+        failmsg="\"Internal : could not get '$argname' in function arguments\""
+        posfailmsg="Internal: positional argument '$argname' encountered after optional argument(s)"
+
+        if [[ "$argname" =~ ^\? ]]; then
+            echo "$SYNTAXLIB_scope ${argname:1}=$argone; shift || :"
+            pos_ok=false
+
+        elif [[ "$argname" =~ ^\* ]]; then
+            [[ "$pos_ok" != false ]] || out:fail "$posfailmsg"
+            echo "declare -n${dec_scope} ${argname:1}=$argone; shift || out:fail $failmsg"
+
+        else
+            [[ "$pos_ok" != false ]] || out:fail "$posfailmsg"
+            echo "$SYNTAXLIB_scope ${argname}=$argone; shift || out:fail $failmsg"
+        fi
+
+        argidx=$((argidx + 1))
+    done
+}
+
+
+### syntax-extensions:use:local FUNCNAME ARGNAMES ... Usage:syntax
+# 
+# Enables syntax macro: function signatures
+#   e.g. $%function func(var1 var2) { ... }
+#
+# Build with bbuild to leverage this function's use:
+#
+#   #%include out.sh
+#   #%include syntax-extensions.sh
+#
+#   $%function person(name email) {
+#       echo "$name <$email>"
+#
+#       # $1 and $2 have been consumed into $name and $email
+#       # The rest remains available in $* :
+#       
+#       echo "Additional notes: $*"
+#   }
+#
+#   person "Jo Smith" "jsmith@example.com" Some details
+#
+###/doc
+syntax-extensions:use:local() {
+    SYNTAXLIB_scope=local syntax-extensions:use "$@"
+}
+
+args:use:local() {
+    syntax-extensions:use:local "$@"
+}
+
+##bash-libs: autohelp.sh @ 69724119 (2.0)
+
+### Autohelp Usage:bbuild
+#
+# Autohelp provides some simple facilities for defining help as comments in your code.
+# It provides several functions for printing specially formatted comment sections.
+#
+# Write your help as documentation comments in your script
+#
+# To output a named section from your script, or a file, call the
+# `autohelp:print` function and it will print the help documentation
+# in the current script, or specified file, to stdout
+#
+# A help comment looks like this:
+#
+#    ### <title> Usage:help
+#    #
+#    # <some content>
+#    #
+#    # end with "###/doc" on its own line (whitespaces before
+#    # and after are OK)
+#    #
+#    ###/doc
+#
+# It can then be printed from the same script by simply calling
+#
+#   autohelp:print
+#
+# You can print a different section by specifying a different name
+#
+# 	autohelp:print section2
+#
+# > This would print a section defined in this way:
+#
+# 	### Some title Usage:section2
+# 	# <some content>
+# 	###/doc
+#
+# You can set a different comment character by setting the 'HELPCHAR' environment variable.
+# Typically, you might want to print comments you set in a INI config file, for example
+#
+# 	HELPCHAR=";" autohelp:print help config-file.ini
+# 
+# Which would then find comments defined like this in `config-file.ini`:
+#
+#   ;;; Main config Usage:help
+#   ; Help comments in a config file
+#   ; may start with a different comment character
+#   ;;;/doc
+#
+#
+#
+# Example usage in a multi-function script:
+#
+#   #!usr/bin/env bash
+#
+#   ### Main help Usage:help
+#   # The main help
+#   ###/doc
+#
+#   ### Feature One Usage:feature_1
+#   # Help text for the first feature
+#   ###/doc
+#
+#   feature1() {
+#       autohelp:check:section feature_1 "$@"
+#       echo "Feature I"
+#   }
+#
+#   ### Feature Two Usage:feature_2
+#   # Help text for the second feature
+#   ###/doc
+#
+#   feature2() {
+#       autohelp:check:section feature_2 "$@"
+#       echo "Feature II"
+#   }
+#
+#   main() {
+#       case "$1" in
+#       feature1|feature2)
+#           "$1" "$@"            # Pass the global script arguments through
+#           ;;
+#       *)
+#           autohelp:check-no-null "$@"  # Check if main help was asked for, if so, or if no args, exit with help
+#
+#           # Main help not requested, return error
+#           echo "Unknown feature"
+#           exit 1
+#           ;;
+#       esac
+#   }
+#
+#   main "$@"
+#
+###/doc
+
+### autohelp:print [ SECTION [FILE] ] Usage:bbuild
+# Print the specified section, in the specified file.
+#
+# If no file is specified, prints for current script file.
+# If no section is specified, defaults to "help"
+###/doc
+
+HELPCHAR='#'
+
+autohelp:print() {
+    local input_line
+    local section_string="${1:-}"; shift || :
+    local target_file="${1:-}"; shift || :
+    [[ -n "$section_string" ]] || section_string=help
+    [[ -n "$target_file" ]] || target_file="$0"
+
+    local sec_start='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s+(.+?)\s+Usage:'"$section_string"'\s*$'
+    local sec_end='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s*/doc\s*$'
+    local in_section=false
+
+    while read input_line; do
+        if [[ "$input_line" =~ $sec_start ]]; then
+            in_section=true
+            echo -e "\n${BASH_REMATCH[1]}\n======="
+
+        elif [[ "$in_section" = true ]]; then
+            if [[ "$input_line" =~ $sec_end ]]; then
+                in_section=false
+            else
+                echo "$input_line" | sed -r "s/^\s*$HELPCHAR/ /;s/^  (\S)/\1/"
+            fi
+        fi
+    done < "$target_file"
+
+    if [[ "$in_section" = true ]]; then
+            out:fail "Non-terminated help block."
+    fi
+}
+
+### autohelp:paged Usage:bbuild
+#
+# Display the help in the pager defined in the PAGER environment variable
+#
+###/doc
+autohelp:paged() {
+    : ${PAGER=less}
+    autohelp:print "$@" | $PAGER
+}
+
+### autohelp:check-or-null ARGS ... Usage:bbuild
+# Print help if arguments are empty, or if arguments contain a '--help' token
+#
+###/doc
+autohelp:check-or-null() {
+    if [[ -z "$*" ]]; then
+        autohelp:print help "$0"
+        exit 0
+    else
+        autohelp:check:section "help" "$@"
+    fi
+}
+
+### autohelp:check-or-null:section SECTION ARGS ... Usage:bbuild
+# Print help section SECTION if arguments are empty, or if arguments contain a '--help' token
+#
+###/doc
+autohelp:check-or-null:section() {
+    . <(args:use:local section -- "$@") ; 
+    if [[ -z "$*" ]]; then
+        autohelp:print "$section" "$0"
+        exit 0
+    else
+        autohelp:check:section "$section" "$@"
+    fi
+}
+
+### autohelp:check ARGS ... Usage:bbuild
+#
+# Automatically print "help" sections and exit, if "--help" is detected in arguments
+#
+###/doc
+autohelp:check() {
+    autohelp:check:section "help" "$@"
+}
+
+### autohelp:check:section SECTION ARGS ... Usage:bbuild
+# Automatically print documentation for named section and exit, if "--help" is detected in arguments
+#
+###/doc
+autohelp:check:section() {
+    local section arg
+    section="${1:-}"; shift || out:fail "No help section specified"
+
+    for arg in "$@"; do
+        if [[ "$arg" =~ --help ]]; then
+            cols="$(tput cols)"
+            autohelp:print "$section" | fold -w "$cols" -s || autohelp:print "$section"
+            exit 0
+        fi
+    done
+}
+
+##bash-libs: searchpaths.sh @ 69724119 (2.0)
 
 # FIXME - set function signature in head of help
 ### searchpaths:file_from PATHDEF FILE Usage:bbuild
