Fix bootstrap silent fail, update installer
* bootstrap-bbuild5 was failing silently when it could not find a file, fixed
    * this was not an issue in new bbuild5, which used a new implementation of includefile
* Updated installer to use options for controlling build and installation
* src/bbuild and bootstrapping bbuild now have toggle to prevent loading of environment file
* bump version

diff --git a/bootstrap/bootstrap-bbuild5 b/bootstrap/bootstrap-bbuild5
--- a/bootstrap/bootstrap-bbuild5
+++ b/bootstrap/bootstrap-bbuild5
@@ -577,7 +577,7 @@ includefile:_cat_once() {
 	for item in "$@"; do
 		[[ -n "$item" ]] || continue
 
-		fullpath="$(searchpaths:file_from "$INCLUDEFILE_paths" "$item")"
+		fullpath="$(searchpaths:file_from "$INCLUDEFILE_paths" "$item")" || out:fail "Error including '$item'"
 		if [[ -z "$fullpath" ]]; then
 			return 1
 		fi
@@ -676,6 +676,9 @@ setup_build_dir() {
 }
 
 load_project_environment() {
+    # preventer is not true || or if it is, bail
+    [[ "${NO_LOAD_BBUILDRC:-}" != true ]] || return 0
+
 	if [[ -f  "$BBUILD_ENV_FILE" ]]; then
 		. "$BBUILD_ENV_FILE" || out:fail "Error during inclusion of environment file."
 	fi
@@ -816,6 +819,7 @@ main() {
 	fi
 	
 	out:debug "And so, processing ${BBFILES[*]}"
+
 
 	for infile in "${BBFILES[@]}"; do
 		build_script "$infile"
